// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blog/search/proto/search/search.proto

package go_micro_service_search

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Document struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b3e81ee7c8420c0, []int{0}
}

func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (m *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(m, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Document) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type IndexRequest struct {
	Document             *Document `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *IndexRequest) Reset()         { *m = IndexRequest{} }
func (m *IndexRequest) String() string { return proto.CompactTextString(m) }
func (*IndexRequest) ProtoMessage()    {}
func (*IndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b3e81ee7c8420c0, []int{1}
}

func (m *IndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexRequest.Unmarshal(m, b)
}
func (m *IndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexRequest.Marshal(b, m, deterministic)
}
func (m *IndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexRequest.Merge(m, src)
}
func (m *IndexRequest) XXX_Size() int {
	return xxx_messageInfo_IndexRequest.Size(m)
}
func (m *IndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IndexRequest proto.InternalMessageInfo

func (m *IndexRequest) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type IndexResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexResponse) Reset()         { *m = IndexResponse{} }
func (m *IndexResponse) String() string { return proto.CompactTextString(m) }
func (*IndexResponse) ProtoMessage()    {}
func (*IndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b3e81ee7c8420c0, []int{2}
}

func (m *IndexResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexResponse.Unmarshal(m, b)
}
func (m *IndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexResponse.Marshal(b, m, deterministic)
}
func (m *IndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexResponse.Merge(m, src)
}
func (m *IndexResponse) XXX_Size() int {
	return xxx_messageInfo_IndexResponse.Size(m)
}
func (m *IndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IndexResponse proto.InternalMessageInfo

type SearchRequest struct {
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b3e81ee7c8420c0, []int{3}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

type SearchResponse struct {
	Documents            []*Document `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b3e81ee7c8420c0, []int{4}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetDocuments() []*Document {
	if m != nil {
		return m.Documents
	}
	return nil
}

func init() {
	proto.RegisterType((*Document)(nil), "go.micro.service.search.Document")
	proto.RegisterType((*IndexRequest)(nil), "go.micro.service.search.IndexRequest")
	proto.RegisterType((*IndexResponse)(nil), "go.micro.service.search.IndexResponse")
	proto.RegisterType((*SearchRequest)(nil), "go.micro.service.search.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "go.micro.service.search.SearchResponse")
}

func init() {
	proto.RegisterFile("blog/search/proto/search/search.proto", fileDescriptor_4b3e81ee7c8420c0)
}

var fileDescriptor_4b3e81ee7c8420c0 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4d, 0xca, 0xc9, 0x4f,
	0xd7, 0x2f, 0x4e, 0x4d, 0x2c, 0x4a, 0xce, 0xd0, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x87, 0x71, 0x20,
	0x94, 0x1e, 0x58, 0x4c, 0x48, 0x3c, 0x3d, 0x5f, 0x2f, 0x37, 0x33, 0xb9, 0x28, 0x5f, 0xaf, 0x38,
	0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0x0f, 0x22, 0xad, 0xa4, 0xc7, 0xc5, 0xe1, 0x92, 0x9f, 0x5c,
	0x9a, 0x9b, 0x9a, 0x57, 0x22, 0xc4, 0xc7, 0xc5, 0x94, 0x99, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1,
	0x19, 0xc4, 0x94, 0x99, 0x22, 0x24, 0xc4, 0xc5, 0x52, 0x92, 0x5a, 0x51, 0x22, 0xc1, 0x04, 0x16,
	0x01, 0xb3, 0x95, 0x7c, 0xb9, 0x78, 0x3c, 0xf3, 0x52, 0x52, 0x2b, 0x82, 0x52, 0x0b, 0x4b, 0x53,
	0x8b, 0x4b, 0x84, 0x6c, 0xb9, 0x38, 0x52, 0xa0, 0xfa, 0xc1, 0x3a, 0xb9, 0x8d, 0x14, 0xf5, 0x70,
	0xd8, 0xa5, 0x07, 0xb3, 0x28, 0x08, 0xae, 0x45, 0x89, 0x9f, 0x8b, 0x17, 0x6a, 0x5c, 0x71, 0x41,
	0x7e, 0x5e, 0x71, 0xaa, 0x92, 0x26, 0x17, 0x6f, 0x30, 0x58, 0x35, 0xcc, 0x02, 0x09, 0x2e, 0xf6,
	0xec, 0xd4, 0xca, 0xf2, 0xfc, 0x22, 0x98, 0xcb, 0x60, 0x5c, 0xa5, 0x40, 0x2e, 0x3e, 0x98, 0x52,
	0x88, 0x66, 0x21, 0x7b, 0x2e, 0x4e, 0x98, 0xc9, 0xc5, 0x12, 0x8c, 0x0a, 0xcc, 0xc4, 0xb9, 0x06,
	0xa1, 0xc7, 0xe8, 0x18, 0x23, 0xcc, 0xfa, 0x60, 0x88, 0x62, 0xa1, 0x08, 0x2e, 0x56, 0xb0, 0x03,
	0x85, 0x54, 0x71, 0x1a, 0x84, 0x1c, 0x1e, 0x52, 0x6a, 0x84, 0x94, 0x41, 0xfd, 0xc9, 0x20, 0x14,
	0xcd, 0xc5, 0x06, 0xb1, 0x4a, 0x08, 0xb7, 0x1e, 0x94, 0xa0, 0x90, 0x52, 0x27, 0xa8, 0x0e, 0x66,
	0x78, 0x12, 0x1b, 0x38, 0xda, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x29, 0x4b, 0x9a, 0xe4,
	0x1f, 0x02, 0x00, 0x00,
}
