// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blog/tags/proto/tags/tags.proto

package go_micro_service_tags

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Tag struct {
	// The id of the parent object
	ParentID string `protobuf:"bytes,1,opt,name=parentID,proto3" json:"parentID,omitempty"`
	// Type is useful for namespacing and listing across parents,
	// ie. list tags for posts, customers etc.
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Slug                 string   `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Count                int64    `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_9135164127924065, []int{0}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetParentID() string {
	if m != nil {
		return m.ParentID
	}
	return ""
}

func (m *Tag) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Tag) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Tag) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Tag) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type IncreaseCountRequest struct {
	ParentID             string   `protobuf:"bytes,1,opt,name=parentID,proto3" json:"parentID,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncreaseCountRequest) Reset()         { *m = IncreaseCountRequest{} }
func (m *IncreaseCountRequest) String() string { return proto.CompactTextString(m) }
func (*IncreaseCountRequest) ProtoMessage()    {}
func (*IncreaseCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9135164127924065, []int{1}
}

func (m *IncreaseCountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncreaseCountRequest.Unmarshal(m, b)
}
func (m *IncreaseCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncreaseCountRequest.Marshal(b, m, deterministic)
}
func (m *IncreaseCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncreaseCountRequest.Merge(m, src)
}
func (m *IncreaseCountRequest) XXX_Size() int {
	return xxx_messageInfo_IncreaseCountRequest.Size(m)
}
func (m *IncreaseCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IncreaseCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IncreaseCountRequest proto.InternalMessageInfo

func (m *IncreaseCountRequest) GetParentID() string {
	if m != nil {
		return m.ParentID
	}
	return ""
}

func (m *IncreaseCountRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *IncreaseCountRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type IncreaseCountResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncreaseCountResponse) Reset()         { *m = IncreaseCountResponse{} }
func (m *IncreaseCountResponse) String() string { return proto.CompactTextString(m) }
func (*IncreaseCountResponse) ProtoMessage()    {}
func (*IncreaseCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9135164127924065, []int{2}
}

func (m *IncreaseCountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncreaseCountResponse.Unmarshal(m, b)
}
func (m *IncreaseCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncreaseCountResponse.Marshal(b, m, deterministic)
}
func (m *IncreaseCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncreaseCountResponse.Merge(m, src)
}
func (m *IncreaseCountResponse) XXX_Size() int {
	return xxx_messageInfo_IncreaseCountResponse.Size(m)
}
func (m *IncreaseCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IncreaseCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IncreaseCountResponse proto.InternalMessageInfo

type DecreaseCountRequest struct {
	ParentID             string   `protobuf:"bytes,1,opt,name=parentID,proto3" json:"parentID,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecreaseCountRequest) Reset()         { *m = DecreaseCountRequest{} }
func (m *DecreaseCountRequest) String() string { return proto.CompactTextString(m) }
func (*DecreaseCountRequest) ProtoMessage()    {}
func (*DecreaseCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9135164127924065, []int{3}
}

func (m *DecreaseCountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecreaseCountRequest.Unmarshal(m, b)
}
func (m *DecreaseCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecreaseCountRequest.Marshal(b, m, deterministic)
}
func (m *DecreaseCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecreaseCountRequest.Merge(m, src)
}
func (m *DecreaseCountRequest) XXX_Size() int {
	return xxx_messageInfo_DecreaseCountRequest.Size(m)
}
func (m *DecreaseCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DecreaseCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DecreaseCountRequest proto.InternalMessageInfo

func (m *DecreaseCountRequest) GetParentID() string {
	if m != nil {
		return m.ParentID
	}
	return ""
}

func (m *DecreaseCountRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *DecreaseCountRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type DecreaseCountResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecreaseCountResponse) Reset()         { *m = DecreaseCountResponse{} }
func (m *DecreaseCountResponse) String() string { return proto.CompactTextString(m) }
func (*DecreaseCountResponse) ProtoMessage()    {}
func (*DecreaseCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9135164127924065, []int{4}
}

func (m *DecreaseCountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecreaseCountResponse.Unmarshal(m, b)
}
func (m *DecreaseCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecreaseCountResponse.Marshal(b, m, deterministic)
}
func (m *DecreaseCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecreaseCountResponse.Merge(m, src)
}
func (m *DecreaseCountResponse) XXX_Size() int {
	return xxx_messageInfo_DecreaseCountResponse.Size(m)
}
func (m *DecreaseCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DecreaseCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DecreaseCountResponse proto.InternalMessageInfo

type UpdateRequest struct {
	ParentID             string   `protobuf:"bytes,1,opt,name=parentID,proto3" json:"parentID,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9135164127924065, []int{5}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetParentID() string {
	if m != nil {
		return m.ParentID
	}
	return ""
}

func (m *UpdateRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *UpdateRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type UpdateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9135164127924065, []int{6}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

// ListRequest: list either by parent id or type.
// Optionally filter by min or max count.
type ListRequest struct {
	ParentID             string   `protobuf:"bytes,1,opt,name=parentID,proto3" json:"parentID,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	MinCount             int64    `protobuf:"varint,3,opt,name=minCount,proto3" json:"minCount,omitempty"`
	MaxCount             int64    `protobuf:"varint,4,opt,name=maxCount,proto3" json:"maxCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9135164127924065, []int{7}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetParentID() string {
	if m != nil {
		return m.ParentID
	}
	return ""
}

func (m *ListRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ListRequest) GetMinCount() int64 {
	if m != nil {
		return m.MinCount
	}
	return 0
}

func (m *ListRequest) GetMaxCount() int64 {
	if m != nil {
		return m.MaxCount
	}
	return 0
}

type ListResponse struct {
	Tags                 []*Tag   `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9135164127924065, []int{8}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*Tag)(nil), "go.micro.service.tags.Tag")
	proto.RegisterType((*IncreaseCountRequest)(nil), "go.micro.service.tags.IncreaseCountRequest")
	proto.RegisterType((*IncreaseCountResponse)(nil), "go.micro.service.tags.IncreaseCountResponse")
	proto.RegisterType((*DecreaseCountRequest)(nil), "go.micro.service.tags.DecreaseCountRequest")
	proto.RegisterType((*DecreaseCountResponse)(nil), "go.micro.service.tags.DecreaseCountResponse")
	proto.RegisterType((*UpdateRequest)(nil), "go.micro.service.tags.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "go.micro.service.tags.UpdateResponse")
	proto.RegisterType((*ListRequest)(nil), "go.micro.service.tags.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "go.micro.service.tags.ListResponse")
}

func init() { proto.RegisterFile("blog/tags/proto/tags/tags.proto", fileDescriptor_9135164127924065) }

var fileDescriptor_9135164127924065 = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xcf, 0x4b, 0xfb, 0x30,
	0x18, 0xc6, 0xd7, 0x6f, 0xba, 0xb1, 0xef, 0x3b, 0x27, 0x12, 0x36, 0x2c, 0xbd, 0x38, 0xaa, 0xc2,
	0x40, 0xc9, 0x60, 0xde, 0xbd, 0xb8, 0xcb, 0xc0, 0x8b, 0x65, 0xc3, 0x8b, 0x97, 0xac, 0x86, 0x50,
	0xe8, 0x9a, 0xda, 0xa4, 0xa2, 0xff, 0x84, 0x7f, 0xb3, 0x24, 0xe9, 0xca, 0x36, 0x5a, 0x7f, 0xa1,
	0x97, 0x91, 0xe7, 0x79, 0xdf, 0xbc, 0x9f, 0x2c, 0x79, 0x28, 0x9c, 0xac, 0x12, 0xc1, 0x27, 0x8a,
	0x72, 0x39, 0xc9, 0x72, 0xa1, 0x84, 0x5d, 0xea, 0x1f, 0x62, 0x34, 0x1e, 0x72, 0x41, 0xd6, 0x71,
	0x94, 0x0b, 0x22, 0x59, 0xfe, 0x1c, 0x47, 0x8c, 0xe8, 0x62, 0x50, 0x00, 0x5a, 0x50, 0x8e, 0x7d,
	0xe8, 0x66, 0x34, 0x67, 0xa9, 0x9a, 0xcf, 0x3c, 0x67, 0xe4, 0x8c, 0xff, 0x87, 0x95, 0xc6, 0x18,
	0x5c, 0xf5, 0x9a, 0x31, 0xef, 0x9f, 0xf1, 0xcd, 0x5a, 0x7b, 0x32, 0x29, 0xb8, 0x87, 0xac, 0xa7,
	0xd7, 0x78, 0x00, 0x6d, 0x15, 0xab, 0x84, 0x79, 0xae, 0x31, 0xad, 0xd0, 0x6e, 0x24, 0x8a, 0x54,
	0x79, 0xed, 0x91, 0x33, 0x46, 0xa1, 0x15, 0xc1, 0x03, 0x0c, 0xe6, 0x69, 0x94, 0x33, 0x2a, 0xd9,
	0x8d, 0x36, 0x42, 0xf6, 0x54, 0x30, 0xa9, 0xbe, 0x7d, 0x8e, 0x8a, 0x89, 0xb6, 0x98, 0xc1, 0x31,
	0x0c, 0xf7, 0xa6, 0xcb, 0x4c, 0xa4, 0x92, 0x69, 0xec, 0x8c, 0xfd, 0x25, 0x76, 0x6f, 0x7a, 0x89,
	0x5d, 0x42, 0x7f, 0x99, 0x3d, 0x52, 0xc5, 0x7e, 0x97, 0x77, 0x04, 0x87, 0x9b, 0xb1, 0x25, 0xa8,
	0x80, 0xde, 0x6d, 0x2c, 0x7f, 0xfc, 0xb7, 0x7c, 0xe8, 0xae, 0xe3, 0xd4, 0x9c, 0xdd, 0x90, 0x50,
	0x58, 0x69, 0x53, 0xa3, 0x2f, 0xb6, 0xe6, 0x96, 0xb5, 0x52, 0x07, 0xd7, 0x70, 0x60, 0xb1, 0xf6,
	0x18, 0x98, 0x80, 0xab, 0xc3, 0xe5, 0x39, 0x23, 0x34, 0xee, 0x4d, 0x7d, 0x52, 0x1b, 0x3d, 0xb2,
	0xa0, 0x3c, 0x34, 0x7d, 0xd3, 0x37, 0x04, 0xee, 0x82, 0x72, 0x89, 0x13, 0xe8, 0xef, 0x3c, 0x1c,
	0xbe, 0x68, 0xd8, 0x5b, 0x17, 0x1e, 0xff, 0xf2, 0x6b, 0xcd, 0xe5, 0x5d, 0xb5, 0x34, 0x6d, 0xe7,
	0xbd, 0x1a, 0x69, 0x75, 0x99, 0x69, 0xa4, 0xd5, 0x47, 0xa0, 0x85, 0xef, 0xc0, 0xd5, 0x97, 0x84,
	0x83, 0x86, 0x7d, 0x5b, 0x0f, 0xe7, 0x9f, 0x7e, 0xd8, 0x53, 0x8d, 0xbc, 0x87, 0x8e, 0x0d, 0x00,
	0x3e, 0x6b, 0xd8, 0xb0, 0x13, 0x3b, 0xff, 0xfc, 0x93, 0xae, 0xcd, 0xe0, 0x55, 0xc7, 0x7c, 0x33,
	0xae, 0xde, 0x03, 0x00, 0x00, 0xff, 0xff, 0x58, 0x4a, 0xf2, 0x38, 0x56, 0x04, 0x00, 0x00,
}
